export const COMMUNITY_RULE_MAX_COUNT = 50;
export const COMMUNITY_RULE_MIN_ORDER = 0;
export const COMMUNITY_RULE_MAX_ORDER = 10_000;
export const COMMUNITY_RULE_MAX_TITLE_LENGTH = 120;
export const COMMUNITY_RULE_MAX_DESCRIPTION_LENGTH = 1_000;
export const COMMUNITY_RULE_TRANSACTION_MAX_ATTEMPTS = 3;
